version: '3.9'

services:
  php:
    container_name: php2
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - "./html:/var/www/html"
    networks:
      - app_network
    depends_on:
      - mysql
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "8085:80"
  services:
  nginx:
    image: nginx
    ports:
      - "8085:80"  # Peta port 8085 host ke port 80 di container
    volumes:
      - "C:/Users/Acer/OneDrive/TUGAS/DockerProject/html:/var/www/html"
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - php

  mysql:
    image: mysql:latest  # Perbaikan indentasi disini
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: gruww
      MYSQL_DATABASE: db
      MYSQL_USER: gres
      MYSQL_PASSWORD: gruw123
    volumes:
      - mysql_volume2:/var/lib/mysql
    ports:
      - "3309:3306"  # Pemetaan port untuk MySQL
    networks:
      - app_network
  
  phpmyadmin:
    container_name: phpmyadmin_2
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8083:80"  # Akses phpMyAdmin di port 8081
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=123456
    depends_on:
      - mysql
    networks:
      - app_network
volumes:
  mysql_volume2:

networks:
  app_network:
    driver: bridge
